apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-a
  namespace: apps
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: service-a
      previewService: service-a-preview
  selector:
    matchLabels:
      app: microservice-a
      app.kubernetes.io/name: microservice-a
      app.kubernetes.io/part-of: microservices
  template:
    metadata:
      labels:
        app: microservice-a
        app.kubernetes.io/name: microservice-a
        app.kubernetes.io/part-of: microservices
    spec:
      initContainers:
        - name: install-otel
          image: node:20-alpine
          command:
            - npm
            - install
            - --prefix
            - /otel
            - --no-fund
            - --no-audit
            - --omit=dev
            - "@opentelemetry/auto-instrumentations-node"
          volumeMounts:
            - name: otel-modules
              mountPath: /otel
      containers:
        - name: node-app
          image: node:20-alpine
          workingDir: /app
          command: ["node", "app.js"]
          ports:
            - name: http
              containerPort: 80
          env:
            - name: OTEL_SERVICE_NAME
              value: microservice-a
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring.svc.cluster.local:4318
            - name: SERVICE_B_URL
              value: http://service-b.apps.svc.cluster.local/
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: NODE_PATH
              value: /otel/node_modules
            - name: NODE_OPTIONS
              value: --require @opentelemetry/auto-instrumentations-node/register
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: env,host,os,process,container
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
          volumeMounts:
            - name: app-config
              mountPath: /app/app.js
              subPath: app.js
            - name: otel-modules
              mountPath: /otel
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
      volumes:
        - name: app-config
          configMap:
            name: microservice-a-app
            items:
              - key: app.js
                path: app.js
        - name: otel-modules
          emptyDir: {}
