apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-a
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: https://github.com/charalamposlamprou/kind-gitops-cluster.git
    targetRevision: test-1234
    path: applications/microservices/microservice-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
