apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: microservice-b
  namespace: apps
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: service-b
      previewService: service-b-preview
  selector:
    matchLabels:
      app: microservice-b
      app.kubernetes.io/name: microservice-b
      app.kubernetes.io/part-of: microservices
  template:
    metadata:
      labels:
        app: microservice-b
        app.kubernetes.io/name: microservice-b
        app.kubernetes.io/part-of: microservices
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: index-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: index-html
          configMap:
            name: microservice-b-html
            items:
              - key: index.html
                path: index.html
