apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring-namespace.yaml
  - prometheus-crds-application.yaml
  - kube-prometheus-stack-application.yaml
  - loki-application.yaml
  - tempo-application.yaml
  - otel-collector-application.yaml
  - ingress-monitoring.yaml
